
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimpleMenuEditor.java
 *
 * Created on Nov 21, 2014, 1:55:55 PM
 */
/**
 *
 * @author user
 */
public class SimpleMenuEditor2 extends javax.swing.JFrame {

    /** Creates new form SimpleMenuEditor */
    public SimpleMenuEditor2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        message = new javax.swing.JLabel();
        Filename = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jDialog3 = new javax.swing.JDialog();
        Smessage = new javax.swing.JLabel();
        NFilename = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jFileOpen = new javax.swing.JFileChooser();
        jFileSave = new javax.swing.JFileChooser();
        jOverwrite = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jOpen = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSave = new javax.swing.JMenuItem();
        jSaveAs = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message.setText("Ορίστε όνομα και διαδρομή αρχείου");
        jDialog1.getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jDialog1.getContentPane().add(Filename, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, -1));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 100, 70, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 12));
        jTextArea2.setRows(5);
        jTextArea2.setText("Η εφαρμογή αυτή δημιουργήθηκε\nαπό τον Π.Νικόλαο στις 21/11/2014\n");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );

        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Smessage.setText("Δώστε το όνομα του νέου αρχειόυ");
        jDialog3.getContentPane().add(Smessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        NFilename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NFilenameActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(NFilename, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, -1));

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, -1));

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 100, 80, -1));

        jFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileOpenActionPerformed(evt);
            }
        });

        jFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileSaveActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("File");

        jOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jOpen.setMnemonic('O');
        jOpen.setText("Open");
        jOpen.setToolTipText("Open a Text File");
        jOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jOpen);

        jMenuItem2.setText("Close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jSave.setMnemonic('S');
        jSave.setText("Save");
        jSave.setToolTipText("Save a Text File");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jSave);

        jSaveAs.setText("Save As");
        jSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveAsActionPerformed(evt);
            }
        });
        jMenu1.add(jSaveAs);
        jMenu1.add(jSeparator2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setMnemonic('E');
        jMenuItem5.setText("Exit");
        jMenuItem5.setToolTipText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setMnemonic('C');
        jMenuItem6.setText("Copy");
        jMenuItem6.setToolTipText("Copy a Text Area");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setMnemonic('P');
        jMenuItem7.setText("Paste");
        jMenuItem7.setToolTipText("Paste the Copied Text Area");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setMnemonic('X');
        jMenuItem8.setText("Cut");
        jMenuItem8.setToolTipText("Cut a Text Area");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem9.setText("About");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    FileReader fw;
    FileWriter f2;
    String filen;
    int returnVal;
    File fileObject;
private void jOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpenActionPerformed
    returnVal = jFileOpen.showOpenDialog(this);
}//GEN-LAST:event_jOpenActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    System.exit(0);
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jDialog1.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
    //String filen = Filename.getText();
    /*if(filen.equals(""))
        message.setText("ERROR");
    else{
        try{
            f2 = new FileWriter(filen);
            jTextArea1.write(f2);
            f2.close();
            message.setText("Ok");
        } catch(IOException exc){
            message.setText(exc.getMessage());
        }        
    }*/
    
    if(fileObject==null){
        returnVal = jFileSave.showSaveDialog(this);
    }else if(fileObject.exists()){
        mysave();
    }
}//GEN-LAST:event_jSaveActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jMenuItem2ActionPerformed

void mysave(){
    int result = jOverwrite.showConfirmDialog(this,"The file exists, overwrite?", "Existing file", JOptionPane.YES_NO_CANCEL_OPTION);
    switch(result){
        case JOptionPane.YES_OPTION:
            FileWriter fw;
            try{
            fw = new FileWriter(filen);
            jTextArea1.write(fw);
            fw.close();
        } catch(IOException exc){
                myerrormessage(exc.getMessage());
            }
            return;
        case JOptionPane.NO_OPTION:
            returnVal = jFileSave.showSaveDialog(this);
            return;
        case JOptionPane.CLOSED_OPTION:
            return;
        case JOptionPane.CANCEL_OPTION:
            return;
    }
}

void myerrormessage(String message){
    JOptionPane.showMessageDialog(null, message, "Prosoxi Lathos", JOptionPane.ERROR_MESSAGE);
}

void myinfomessage(String message){
    JOptionPane.showMessageDialog(null, message, "Minima", JOptionPane.INFORMATION_MESSAGE);

}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    filen = Filename.getText();
    message.setText("Ορίστε όνομα και διαδρομή αρχείου");
    if(filen.equals(""))
        message.setText("ERROR");
    else{
        try{
            fw = new FileReader(filen);
            jTextArea1.read(fw, null);
            fw.close();
            message.setText("Ok");
            jDialog1.setVisible(false);
        } catch(IOException exc){
            message.setText(exc.getMessage());
        }
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
    jDialog2.setVisible(true);
    jDialog2.setSize(270, 180);
}//GEN-LAST:event_jMenuItem9ActionPerformed

private void NFilenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NFilenameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_NFilenameActionPerformed

private void jSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveAsActionPerformed
    /*jDialog3.setVisible(true);
    jDialog3.setSize(270, 180);*/
    returnVal = jFileSave.showSaveDialog(this);
}//GEN-LAST:event_jSaveAsActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    jDialog3.setVisible(false);
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    filen = NFilename.getText();
    if(filen.equals(""))
        Smessage.setText("ERROR");
    else{
        try{
            f2 = new FileWriter(filen);
            jTextArea1.write(f2);
            f2.close();
            jDialog3.setVisible(false);
            message.setText("Το αρχείο αποθηκεύτικε σωστά");
        } catch(IOException exc){
            Smessage.setText("Λάθος όνομα αρχείου");
            return;
        }        
    }
}//GEN-LAST:event_jButton3ActionPerformed

private void jFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileOpenActionPerformed
    //String filen = jTextField1.getText();
    fileObject = jFileOpen.getSelectedFile();
    if(fileObject !=null && returnVal == JFileChooser.APPROVE_OPTION){
       filen = fileObject.getPath();
       if(filen.length() == 0){
           myinfomessage("Orise onoma kai diadromi");
           return;
       }
       try{
           fw = new FileReader(filen);
           jTextArea1.read(fw, null);
           fw.close();
           setTitle(filen);
       } catch (IOException exc){
           myerrormessage(exc.getMessage());
           return;
       }
       myinfomessage("To arxeio fortothike");
    } else if(fileObject != null && returnVal == JFileChooser.CANCEL_OPTION)
        myinfomessage("You pressed Cancel");
    /*FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT files", "txt");
    jFileOpen.setFileFilter(filter);
    int returnval = jFileOpen.showOpenDialog(this);
    if(returnval == JFileChooser.APPROVE_OPTION){
        filen = jFileOpen.getSelectedFile().getPath();
    if(filen.equals(""))
        myerrormessage("OK");
    else{
        try{
            fw = new FileReader(filen);
            jTextArea1.read(fw, null);
            fw.close();
            myinfomessage("Ok");
        } catch(IOException exc){
            myerrormessage(exc.getMessage());
        }
    
   }
    
   } else if(returnval == JFileChooser.CANCEL_OPTION)
       myinfomessage("You pressed cancel");*/
}//GEN-LAST:event_jFileOpenActionPerformed

private void jFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileSaveActionPerformed
    FileWriter fr;
    if(returnVal == JFileChooser.APPROVE_OPTION){
        fileObject = jFileSave.getSelectedFile();
        if(fileObject == null)
            return;
        filen = fileObject.getPath();
        if(fileObject.exists())
            mysave();
        if(filen.length() == 0){
            myinfomessage("Oriste onoma k diadromi arxeiou");
            return;
        }
        try{
            fr = new FileWriter(filen);
            jTextArea1.write(fr);
            fr.close();
            setTitle(filen);
        } catch(IOException exc){
            myerrormessage("Lathos onoma arxeiou");
            return;
        }
        myinfomessage("to arxeio apothuikeutike swsta");
    } else if(fileObject !=null && returnVal == JFileChooser.CANCEL_OPTION){
        myinfomessage("you pressed cancel");
    } else if()
}//GEN-LAST:event_jFileSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleMenuEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleMenuEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleMenuEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleMenuEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SimpleMenuEditor2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Filename;
    private javax.swing.JTextField NFilename;
    private javax.swing.JLabel Smessage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFileChooser jFileOpen;
    private javax.swing.JFileChooser jFileSave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jOpen;
    private javax.swing.JOptionPane jOverwrite;
    private javax.swing.JMenuItem jSave;
    private javax.swing.JMenuItem jSaveAs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
