
import java.util.Hashtable;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AudioPlayer.java
 *
 * Created on Oct 24, 2014, 1:48:21 PM
 */
/**
 *
 * @author user
 */
public class AudioPlayer extends javax.swing.JFrame {

    class Presets{
        int bass;
        int midrange;
        int tremble;
        int balance;
        int volume;
        
        
        Presets(int bass, int midrange, int tremble, int balance, int volume){
            this.bass=bass;
            this.midrange=midrange;
            this.tremble=tremble;
            this.balance=balance;
            this.volume=volume;
        }
    }
        Presets pinakas[] = new Presets[3];
        
        public void setPresets(){
            pinakas[0] = new Presets(0, 0, 0, 0, 0);
            pinakas[1] = new Presets(1, -1, 9, 0, 4);
            pinakas[2] = new Presets(2, 4, -2, 4, 2);
        }
        
        public void showPresets(){
            String bal = "Center";
            int b = jSlider4.getValue();
            if(b>0)
                bal = "Right " + String.valueOf(b);
            else if(b==0)
                bal = "Center";
            else
                bal = "Left " + String.valueOf(b);
            
            info.setText("<html> Bass :" + SlBass.getValue() +
                    "<br> Midrange :" + jSlider2.getValue() +
                    "<br> Tremble :" + jSlider3.getValue() + 
                    "<br> Balance :" + bal +
                    "<br> Volume :" + jSlider5.getValue());
        }
        
        public void loadPresets(Presets pin){
            SlBass.setValue(pin.bass);
            jSlider2.setValue(pin.midrange);
            jSlider3.setValue(pin.tremble);
            jSlider4.setValue(pin.balance);
            jSlider5.setValue(pin.volume); 
            showPresets();
        }
        
        public void storePresets(Presets data){
            data.bass = SlBass.getValue();
            data.midrange = jSlider2.getValue();
            data.tremble = jSlider3.getValue();
            data.balance = jSlider4.getValue();
            data.volume = jSlider5.getValue();
        
        }
    
    
    
    /** Creates new form AudioPlayer */
    public AudioPlayer() {
        initComponents();
        setPresets();
        showPresets();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        LBass = new javax.swing.JLabel();
        LMidrange = new javax.swing.JLabel();
        LTreble = new javax.swing.JLabel();
        LBalance = new javax.swing.JLabel();
        LVolume = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        SlBass = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        LBass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBass.setText("Bass");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(LBass, gridBagConstraints);

        LMidrange.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LMidrange.setText("Midrange");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        getContentPane().add(LMidrange, gridBagConstraints);

        LTreble.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LTreble.setText("Treble");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        getContentPane().add(LTreble, gridBagConstraints);

        LBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBalance.setText("Balance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        getContentPane().add(LBalance, gridBagConstraints);

        LVolume.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LVolume.setText("Volume");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        getContentPane().add(LVolume, gridBagConstraints);

        info.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        getContentPane().add(info, gridBagConstraints);

        SlBass.setMajorTickSpacing(2);
        SlBass.setMaximum(10);
        SlBass.setMinimum(-10);
        SlBass.setMinorTickSpacing(1);
        SlBass.setPaintLabels(true);
        SlBass.setPaintTicks(true);
        SlBass.setValue(0);
        SlBass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SlBass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SlBassStateChanged(evt);
            }
        });
        getContentPane().add(SlBass, new java.awt.GridBagConstraints());

        jSlider2.setMajorTickSpacing(2);
        jSlider2.setMaximum(10);
        jSlider2.setMinimum(-10);
        jSlider2.setMinorTickSpacing(1);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(0);
        jSlider2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jSlider2, gridBagConstraints);

        jSlider3.setMajorTickSpacing(2);
        jSlider3.setMaximum(10);
        jSlider3.setMinimum(-10);
        jSlider3.setMinorTickSpacing(1);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setValue(0);
        jSlider3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jSlider3, gridBagConstraints);

        jSlider4.setMajorTickSpacing(1);
        jSlider4.setMaximum(5);
        jSlider4.setMinimum(-5);
        jSlider4.setMinorTickSpacing(1);
        jSlider4.setPaintLabels(true);
        jSlider4.setPaintTicks(true);
        jSlider4.setValue(0);
        jSlider4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jSlider4, gridBagConstraints);
        Hashtable table = new Hashtable();
        table.put(new Integer(0), new JLabel("Center"));
        table.put(new Integer(-5), new JLabel("L"));
        table.put(new Integer(5), new JLabel("R"));
        jSlider4.setLabelTable(table);

        jSlider5.setMajorTickSpacing(1);
        jSlider5.setMaximum(10);
        jSlider5.setMinorTickSpacing(1);
        jSlider5.setPaintLabels(true);
        jSlider5.setPaintTicks(true);
        jSlider5.setToolTipText("");
        jSlider5.setValue(0);
        jSlider5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider5StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jSlider5, gridBagConstraints);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Defaults");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Preset1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton2, gridBagConstraints);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Preset2");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jRadioButton3, gridBagConstraints);

        jButton1.setText("Store Settings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    loadPresets(pinakas[0]);
}//GEN-LAST:event_jRadioButton1ActionPerformed

private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    loadPresets(pinakas[1]);
}//GEN-LAST:event_jRadioButton2ActionPerformed

private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
    loadPresets(pinakas[2]);
}//GEN-LAST:event_jRadioButton3ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   /* int b = SlBass.getValue();
    int m = jSlider2.getValue();
    int t = jSlider3.getValue();
    int bl = jSlider4.getValue();
    int v = jSlider5.getValue();
   */ if(jRadioButton2.isSelected())
        storePresets(pinakas[1]);
    else if(jRadioButton3.isSelected())
        storePresets(pinakas[2]);
}//GEN-LAST:event_jButton1ActionPerformed

private void SlBassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SlBassStateChanged
    showPresets();
}//GEN-LAST:event_SlBassStateChanged

private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
    showPresets();
}//GEN-LAST:event_jSlider2StateChanged

private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
    showPresets();
    // TODO add your handling code here:
}//GEN-LAST:event_jSlider3StateChanged

private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
// TODO add your handling code here:
    showPresets();
}//GEN-LAST:event_jSlider4StateChanged

private void jSlider5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider5StateChanged
// TODO add your handling code here:
    showPresets();
}//GEN-LAST:event_jSlider5StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudioPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudioPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudioPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudioPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AudioPlayer().setVisible(true);
            }
        });
    }
    
    Hashtable table = new Hashtable();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBalance;
    private javax.swing.JLabel LBass;
    private javax.swing.JLabel LMidrange;
    private javax.swing.JLabel LTreble;
    private javax.swing.JLabel LVolume;
    private javax.swing.JSlider SlBass;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    // End of variables declaration//GEN-END:variables
}
